name: copper_ai_flutter_sdk
description: "A Copper AI Bot."
version: 0.0.2
homepage: https://github.com/yavar-ai/copper-ai-flutter-sdk

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  get: ^4.6.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: